# Generated by Django 4.2.7 on 2025-11-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerciale', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_travail', models.DateField()),
                ('heures_normales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activite', models.CharField(choices=[('fabrication', 'Fabrication'), ('pose', 'Pose'), ('livraison', 'Livraison'), ('autre', 'Autre')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('valide_le', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures', to='commerciale.chantier')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_travaillees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heure',
                'verbose_name_plural': 'Heures',
                'db_table': 'travaux_heures',
            },
        ),
        migrations.CreateModel(
            name='ChantierTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='commerciale.chantier')),
            ],
            options={
                'verbose_name': 'Chantier travaux',
                'verbose_name_plural': 'Chantiers travaux',
                'db_table': 'travaux_chantiers',
            },
        ),
        migrations.CreateModel(
            name='BilanChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('heures_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avancement_pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='commerciale.chantier')),
            ],
            options={
                'verbose_name': 'Bilan chantier',
                'verbose_name_plural': 'Bilans chantiers',
                'db_table': 'travaux_bilans_chantiers',
            },
        ),
    ]
