# Generated by Django 4.2.7 on 2025-11-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerciale', '0004_alter_facture_numero_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('date_commande', models.DateField()),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('type_travaux', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_travaux', to='commerciale.chantier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_travaux', to='commerciale.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_travaux_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande travaux',
                'verbose_name_plural': 'Commandes travaux',
                'db_table': 'travaux_commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='DevisTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_devis', models.CharField(max_length=50, unique=True)),
                ('date_devis', models.DateField()),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('type_travaux', models.CharField(help_text='Type de travaux (ex: Rénovation, Installation, Réparation)', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20)),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('date_acceptation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_travaux', to='commerciale.chantier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_travaux', to='commerciale.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_travaux_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis travaux',
                'verbose_name_plural': 'Devis travaux',
                'db_table': 'travaux_devis',
                'ordering': ['-date_devis'],
            },
        ),
        migrations.CreateModel(
            name='FactureTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('type_travaux', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('partiellement_payee', 'Partiellement payée'), ('impayee', 'Impayée')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_travaux', to='commerciale.chantier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_travaux', to='commerciale.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='travaux.commandetravaux')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_travaux_crees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='travaux.devistravaux')),
            ],
            options={
                'verbose_name': 'Facture travaux',
                'verbose_name_plural': 'Factures travaux',
                'db_table': 'travaux_factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneFactureTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'mètre linéaire'), ('forfait', 'Forfait')], default='unite', max_length=20)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail_calcul', models.JSONField(default=dict, help_text='Détail du calcul : {main_oeuvre: {heures: 10, taux: 25}, materiaux: [...], autres: [...]}')),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='travaux.facturetravaux')),
            ],
            options={
                'verbose_name': 'Ligne facture travaux',
                'verbose_name_plural': 'Lignes factures travaux',
                'db_table': 'travaux_factures_lignes',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevisTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'mètre linéaire'), ('forfait', 'Forfait')], default='unite', max_length=20)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail_calcul', models.JSONField(default=dict, help_text='Détail du calcul : {main_oeuvre: {heures: 10, taux: 25}, materiaux: [...], autres: [...]}')),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='travaux.devistravaux')),
            ],
            options={
                'verbose_name': 'Ligne devis travaux',
                'verbose_name_plural': 'Lignes devis travaux',
                'db_table': 'travaux_devis_lignes',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='commandetravaux',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='travaux.devistravaux'),
        ),
    ]
