# Generated by Django 4.2.7 on 2025-11-10 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('response_status', models.IntegerField(blank=True, db_index=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée de log',
                'verbose_name_plural': 'Entrées de log',
                'db_table': 'log_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='log_entries_created_ed25c2_idx'), models.Index(fields=['level', 'created_at'], name='log_entries_level_41d97c_idx'), models.Index(fields=['logger_name', 'created_at'], name='log_entries_logger__6cd07b_idx')],
            },
        ),
    ]
