# Generated by Django 5.2 on 2025-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='extra_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
