# Generated by Django 4.2.7 on 2025-11-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('montant', 'Montant'), ('traverse', 'Traverse'), ('raidisseur', 'Raidisseur')], max_length=20)),
                ('materiau', models.CharField(choices=[('alu', 'Aluminium'), ('pvc', 'PVC'), ('bois', 'Bois'), ('acier', 'Acier')], max_length=20)),
                ('dimensions', models.JSONField(default=dict)),
                ('caracteristiques', models.JSONField(default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'db_table': 'inertie_profils',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_projet', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_inertie', to='commerciale.chantier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_inertie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet inertie',
                'verbose_name_plural': 'Projets inertie',
                'db_table': 'inertie_projets',
            },
        ),
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.JSONField(default=dict)),
                ('contraintes', models.JSONField(default=dict)),
                ('validation', models.JSONField(default=dict)),
                ('norme_utilisee', models.CharField(default='NF EN 1991', max_length=50)),
                ('resultat_ei', models.DecimalField(decimal_places=6, max_digits=15)),
                ('contrainte_max', models.DecimalField(decimal_places=6, max_digits=15)),
                ('contrainte_admissible', models.DecimalField(decimal_places=6, max_digits=15)),
                ('valide', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculs', to='inertie.profil')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs', to='inertie.projet')),
            ],
            options={
                'verbose_name': 'Calcul inertie',
                'verbose_name_plural': 'Calculs inertie',
                'db_table': 'inertie_calculs',
            },
        ),
    ]
