# Generated by Django 4.2.7 on 2025-11-06 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inertie', '0002_refactor_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculEI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_charge', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=30)),
                ('module_elasticite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.JSONField(default=dict, help_text='Dimensions selon le type de charge (S1, S2, S3, Q, etc.)')),
                ('categorie_terrain', models.CharField(choices=[('0', 'Catégorie 0'), ('I', 'Catégorie I'), ('II', 'Catégorie II'), ('III', 'Catégorie III'), ('IV', 'Catégorie IV')], default='0', max_length=3)),
                ('e1', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('e2', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('e3', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('charge_exercee', models.DecimalField(blank=True, decimal_places=6, help_text='Charge exercée', max_digits=15, null=True)),
                ('charge_admissible', models.DecimalField(blank=True, decimal_places=6, help_text='Charge admissible', max_digits=15, null=True)),
                ('i_mini', models.DecimalField(blank=True, decimal_places=6, help_text='I mini en cm⁴', max_digits=15, null=True)),
                ('i_reel', models.DecimalField(blank=True, decimal_places=6, help_text='I réel en cm⁴', max_digits=15, null=True)),
                ('i_besoin', models.DecimalField(blank=True, decimal_places=6, help_text='I besoin en cm⁴', max_digits=15, null=True)),
                ('pression_calcul', models.DecimalField(blank=True, decimal_places=2, help_text='Pression de calcul en daN/m²', max_digits=15, null=True)),
                ('norme_utilisee', models.CharField(default='NF EN 1991-1-4:2005', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calcul EI',
                'verbose_name_plural': 'Calculs EI',
                'db_table': 'inertie_calculs_ei',
            },
        ),
        migrations.CreateModel(
            name='CalculRaidisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_calcul', models.CharField(default='NF DTU 30.1 (2008 - fiche Technique N°45/2010)', max_length=200)),
                ('type_charge', models.CharField(choices=[('rectangulaire_2_appuis', 'Rectangulaire sur 2 appuis'), ('encastrement_appui', '1 encastrement et 1 appui'), ('rectangulaire_3_appuis', 'Rectangulaire sur 3 appuis'), ('trapezoidale', 'Trapézoïdale')], max_length=30)),
                ('module_elasticite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portee', models.DecimalField(decimal_places=2, help_text='Portée en mm', max_digits=10)),
                ('trame', models.DecimalField(decimal_places=2, help_text='Trame en mm', max_digits=10)),
                ('fleche_admissible', models.DecimalField(decimal_places=2, help_text='Flèche admissible en mm', max_digits=10)),
                ('region_vent', models.CharField(choices=[('01', 'Région 01'), ('02', 'Région 02'), ('03', 'Région 03'), ('04', 'Région 04')], default='01', max_length=2)),
                ('categorie_terrain', models.CharField(choices=[('0', 'Catégorie 0'), ('I', 'Catégorie I'), ('II', 'Catégorie II'), ('III', 'Catégorie III'), ('IV', 'Catégorie IV')], default='0', max_length=3)),
                ('hauteur_sol', models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur au dessus du sol en m', max_digits=10, null=True)),
                ('pente_toiture', models.DecimalField(blank=True, decimal_places=2, help_text='Pente de toiture en degrés', max_digits=10, null=True)),
                ('pente_obstacles', models.DecimalField(blank=True, decimal_places=2, help_text="Pente d'obstacles voisins en m", max_digits=10, null=True)),
                ('constructions_voisines', models.BooleanField(default=False, help_text='Constructions avoisinantes > 20m')),
                ('region_neige', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('pression_vent', models.DecimalField(blank=True, decimal_places=2, help_text='Pression au vent en Pa', max_digits=10, null=True)),
                ('inertie_requise', models.DecimalField(blank=True, decimal_places=2, help_text='Inertie Ixx requise en cm⁴', max_digits=15, null=True)),
                ('calcul_avec_renfort', models.BooleanField(default=False)),
                ('choix_automatique_profil', models.BooleanField(default=False)),
                ('norme_utilisee', models.CharField(default='NF EN 1991-1-4/NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calcul raidisseur',
                'verbose_name_plural': 'Calculs raidisseur',
                'db_table': 'inertie_calculs_raidisseur',
            },
        ),
        migrations.CreateModel(
            name='CalculTraverse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portee', models.DecimalField(decimal_places=2, help_text='Portée en mm', max_digits=10)),
                ('trame_verticale', models.DecimalField(decimal_places=2, help_text='Trame verticale au dessus de la traverse en mm', max_digits=10)),
                ('poids_remplissage', models.DecimalField(decimal_places=2, help_text='Poids du remplissage en kg/m²', max_digits=10)),
                ('poids_traverse', models.DecimalField(decimal_places=2, help_text='Poids de la traverse en kg/m', max_digits=10)),
                ('distance_blocage', models.DecimalField(decimal_places=2, default=40, help_text='Distance de blocage en mm (défaut 40mm selon NF DTU 39 P1-1)', max_digits=10)),
                ('module_elasticite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_fleche', models.CharField(choices=[('portee_200', 'Portée / 200'), ('portee_300', 'Portée / 300'), ('personnalise', 'Personnalisée')], default='portee_200', max_length=20)),
                ('fleche_admissible', models.DecimalField(decimal_places=2, help_text='Flèche admissible en mm', max_digits=10)),
                ('inertie_requise', models.DecimalField(blank=True, decimal_places=2, help_text='Inertie Iy requise en cm⁴', max_digits=15, null=True)),
                ('choix_automatique_profil', models.BooleanField(default=False)),
                ('norme_utilisee', models.CharField(default='NF DTU 39 P1-1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calcul traverse',
                'verbose_name_plural': 'Calculs traverse',
                'db_table': 'inertie_calculs_traverse',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('projet', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('titre_document', models.CharField(default="Note de calcul d'inertie", max_length=200)),
                ('societe', models.CharField(blank=True, max_length=200)),
                ('fichier_logo', models.CharField(blank=True, max_length=500)),
                ('commentaires', models.TextField(blank=True)),
                ('region_vent_defaut', models.CharField(choices=[('01', 'Région 01'), ('02', 'Région 02'), ('03', 'Région 03'), ('04', 'Région 04')], default='01', max_length=2)),
                ('categorie_terrain_defaut', models.CharField(choices=[('0', 'Catégorie 0'), ('I', 'Catégorie I'), ('II', 'Catégorie II'), ('III', 'Catégorie III'), ('IV', 'Catégorie IV')], default='0', max_length=3)),
                ('neige_defaut', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('norme_calcul', models.CharField(default='NF EN 1991-1-4:2005', max_length=100)),
                ('type_calcul', models.CharField(choices=[('eurocode1', 'Eurocode 1'), ('dtu39', 'DTU 39 P1-1')], default='eurocode1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'inertie_configuration',
            },
        ),
        migrations.AlterField(
            model_name='famillemateriau',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='famillemateriau',
            name='module_elasticite',
            field=models.DecimalField(decimal_places=2, help_text="Module d'élasticité en daN/mm²", max_digits=10),
        ),
        migrations.AlterField(
            model_name='profil',
            name='inertie_ixx',
            field=models.DecimalField(decimal_places=2, help_text='Inertie Ixx en cm⁴', max_digits=15),
        ),
        migrations.AlterField(
            model_name='profil',
            name='inertie_iyy',
            field=models.DecimalField(decimal_places=2, help_text='Inertie Iyy en cm⁴', max_digits=15),
        ),
        migrations.AlterField(
            model_name='profil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Calcul',
        ),
        migrations.AddField(
            model_name='calcultraverse',
            name='famille_materiau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inertie.famillemateriau'),
        ),
        migrations.AddField(
            model_name='calcultraverse',
            name='profil_selectionne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inertie.profil'),
        ),
        migrations.AddField(
            model_name='calcultraverse',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs_traverse', to='inertie.projet'),
        ),
        migrations.AddField(
            model_name='calculraidisseur',
            name='famille_materiau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inertie.famillemateriau'),
        ),
        migrations.AddField(
            model_name='calculraidisseur',
            name='profil_selectionne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inertie.profil'),
        ),
        migrations.AddField(
            model_name='calculraidisseur',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs_raidisseur', to='inertie.projet'),
        ),
        migrations.AddField(
            model_name='calculei',
            name='famille_materiau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inertie.famillemateriau'),
        ),
        migrations.AddField(
            model_name='calculei',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs_ei', to='inertie.projet'),
        ),
    ]
