# Generated by Django 4.2.7 on 2025-11-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
        ('commerciale', '0001_initial'),
        # comptabilite sera ajouté dans une migration ultérieure
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.article'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commerciale.devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='commerciale.chantier'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='commerciale.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='commerciale.devis'),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='commerciale.chantier'),
        ),
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='commerciale.client'),
        ),
        migrations.AddField(
            model_name='devis',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chantier',
            name='chef_chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='commerciale.client'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_commercial', to=settings.AUTH_USER_MODEL),
        ),
    ]
