# Generated by Django 4.2.7 on 2025-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerciale', '0003_add_compte_comptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
