# Generated by Django 4.2.7 on 2025-11-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chariot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('capacite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chariot',
                'verbose_name_plural': 'Chariots',
                'db_table': 'tournees_chariots',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_permis', models.CharField(max_length=50)),
                ('date_expiration_permis', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'db_table': 'tournees_chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre_livraison', models.IntegerField()),
                ('adresse_livraison', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('echec', 'Échec')], default='planifiee', max_length=20)),
                ('date_livraison_prevue', models.DateTimeField()),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='commerciale.chantier')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='commerciale.facture')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'tournees_livraisons',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('utilitaire', 'Utilitaire'), ('camion', 'Camion'), ('fourgon', 'Fourgon')], max_length=20)),
                ('capacite_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'tournees_vehicules',
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tournee', models.CharField(max_length=50, unique=True)),
                ('date_tournee', models.DateField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('itineraire_optimise', models.JSONField(default=dict)),
                ('distance_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_estimee', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='tournees.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='tournees.vehicule')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'db_table': 'tournees_tournees',
            },
        ),
        migrations.CreateModel(
            name='LivraisonChariot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('chariot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournees.chariot')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chariots', to='tournees.livraison')),
            ],
            options={
                'verbose_name': 'Livraison chariot',
                'verbose_name_plural': 'Livraisons chariots',
                'db_table': 'tournees_livraisons_chariots',
            },
        ),
        migrations.AddField(
            model_name='livraison',
            name='tournee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='tournees.tournee'),
        ),
    ]
