# Generated by Django 4.2.7 on 2025-11-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0002_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCoupe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_plan', models.CharField(max_length=50, unique=True)),
                ('type_matiere', models.CharField(choices=[('plaque', 'Plaque'), ('barre', 'Barre')], max_length=20)),
                ('dimensions_plaque', models.JSONField(default=dict)),
                ('dimensions_commandes', models.JSONField(default=dict)),
                ('resultat_optimisation', models.JSONField(default=dict)),
                ('taux_utilisation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chutes_reutilisables', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('envoye_cnc', 'Envoyé CNC')], default='brouillon', max_length=20)),
                ('fichier_cnc_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_coupe', to='commerciale.chantier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_coupe', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_coupe', to='stock.article')),
            ],
            options={
                'verbose_name': 'Plan de coupe',
                'verbose_name_plural': 'Plans de coupe',
                'db_table': 'optimisation_plans_coupe',
            },
        ),
        migrations.CreateModel(
            name='Chute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimensions', models.JSONField(default=dict)),
                ('quantite', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('utilisee', 'Utilisée')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chutes', to='stock.article')),
                ('plan_coupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chutes', to='optimisation.plancoupe')),
            ],
            options={
                'verbose_name': 'Chute',
                'verbose_name_plural': 'Chutes',
                'db_table': 'optimisation_chutes',
            },
        ),
    ]
