# Generated by Django 4.2.7 on 2025-11-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0004_alter_facture_numero_facture'),
        ('optimisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_affaire', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_debit', to='commerciale.chantier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_debit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affaire',
                'verbose_name_plural': 'Affaires',
                'db_table': 'optimisation_affaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_debit', models.CharField(max_length=50)),
                ('largeur_source', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longueur_source', models.DecimalField(decimal_places=2, max_digits=8)),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pieces', models.JSONField(default=list)),
                ('resultat_optimisation', models.JSONField(default=dict)),
                ('plan_coupe', models.JSONField(default=list)),
                ('taux_utilisation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nombre_plaques_necessaires', models.IntegerField(default=1)),
                ('sens_coupe', models.CharField(choices=[('transversal', 'Transversal'), ('longitudinal', 'Longitudinal')], default='transversal', max_length=20)),
                ('chutes_reutilisables', models.JSONField(default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fichier_cnc_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fichier_ascii_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Débit',
                'verbose_name_plural': 'Débits',
                'db_table': 'optimisation_debits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lancement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lancement', models.CharField(max_length=50)),
                ('date_lancement', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('optimise', 'Optimisé'), ('valide', 'Validé'), ('envoye_cnc', 'Envoyé CNC')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancements', to='optimisation.affaire')),
            ],
            options={
                'verbose_name': 'Lancement',
                'verbose_name_plural': 'Lancements',
                'db_table': 'optimisation_lancements',
                'ordering': ['-date_lancement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('type_matiere', models.CharField(choices=[('plaque', 'Plaque'), ('barre', 'Barre'), ('bobine', 'Bobine'), ('panneau', 'Panneau'), ('tole', 'Tôle'), ('vitrage', 'Vitrage'), ('plastique', 'Plastique'), ('autre', 'Autre')], max_length=20)),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('largeur_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('longueur_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unite', models.CharField(default='mm', max_length=10)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'optimisation_matieres',
            },
        ),
        migrations.CreateModel(
            name='ParametresDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('reequerrage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('epaisseur_lame', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('dimension_chute_jetee', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('dimension_chute_facturee', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('sens_coupe_par_defaut', models.CharField(choices=[('transversal', 'Transversal'), ('longitudinal', 'Longitudinal')], default='transversal', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de débit',
                'verbose_name_plural': 'Paramètres de débit',
                'db_table': 'optimisation_parametres_debit',
            },
        ),
        migrations.CreateModel(
            name='StockMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantite', models.IntegerField(default=1)),
                ('quantite_reservee', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('epuise', 'Épuisé')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='optimisation.matiere')),
            ],
            options={
                'verbose_name': 'Stock matière',
                'verbose_name_plural': 'Stocks matières',
                'db_table': 'optimisation_stocks_matiere',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chute', 'verbose_name_plural': 'Chutes'},
        ),
        migrations.RemoveField(
            model_name='chute',
            name='plan_coupe',
        ),
        migrations.AddField(
            model_name='chute',
            name='epaisseur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chute',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chute',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chute',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chute',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chute',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('utilisee', 'Utilisée'), ('jetee', 'Jetée')], default='disponible', max_length=20),
        ),
        migrations.DeleteModel(
            name='PlanCoupe',
        ),
        migrations.AddField(
            model_name='lancement',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancements', to='optimisation.matiere'),
        ),
        migrations.AddField(
            model_name='lancement',
            name='parametres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancements', to='optimisation.parametresdebit'),
        ),
        migrations.AddField(
            model_name='debit',
            name='lancement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='optimisation.lancement'),
        ),
        migrations.AddField(
            model_name='chute',
            name='debit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chutes', to='optimisation.debit'),
        ),
        migrations.AlterField(
            model_name='chute',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chutes', to='optimisation.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='lancement',
            unique_together={('affaire', 'numero_lancement')},
        ),
    ]
