# Generated by Django 5.2 on 2025-11-10 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('acces_commerciale', models.BooleanField(default=False)),
                ('acces_menuiserie', models.BooleanField(default=False)),
                ('acces_vitrages', models.BooleanField(default=False)),
                ('acces_optimisation', models.BooleanField(default=False)),
                ('acces_stock', models.BooleanField(default=False)),
                ('acces_travaux', models.BooleanField(default=False)),
                ('acces_planning', models.BooleanField(default=False)),
                ('acces_tournees', models.BooleanField(default=False)),
                ('acces_crm', models.BooleanField(default=False)),
                ('acces_inertie', models.BooleanField(default=False)),
                ('acces_parametres', models.BooleanField(default=False)),
                ('acces_logs', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'user_groups',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('commercial', 'Commercial'), ('atelier', 'Service technique'), ('ouvrier', 'Ouvrier'), ('logistique', 'Logistique'), ('comptable', 'Comptable')], default='commercial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.group'),
        ),
    ]
