# Generated by Django 4.2.7 on 2025-11-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0002_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('type_article', models.CharField(choices=[('fenetre', 'Fenêtre'), ('porte', 'Porte'), ('baie', 'Baie vitrée'), ('autre', 'Autre')], max_length=20)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profondeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dessin_path', models.CharField(blank=True, max_length=500, null=True)),
                ('options_obligatoires', models.JSONField(default=dict)),
                ('options_facultatives', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article menuiserie',
                'verbose_name_plural': 'Articles menuiserie',
                'db_table': 'menuiserie_articles',
            },
        ),
        migrations.CreateModel(
            name='TarifFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_fournisseur', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('m2', 'm²'), ('ml', 'mètre linéaire'), ('kg', 'Kilogramme')], default='unite', max_length=10)),
                ('date_validite_debut', models.DateField()),
                ('date_validite_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Tarif fournisseur',
                'verbose_name_plural': 'Tarifs fournisseurs',
                'db_table': 'menuiserie_tarifs_fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_projet', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_menuiserie', to='commerciale.chantier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_menuiserie', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_menuiserie', to='commerciale.devis')),
            ],
            options={
                'verbose_name': 'Projet menuiserie',
                'verbose_name_plural': 'Projets menuiserie',
                'db_table': 'menuiserie_projets',
            },
        ),
        migrations.CreateModel(
            name='Dessin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier_path', models.CharField(max_length=500)),
                ('echelle', models.CharField(max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('dwg', 'DWG'), ('dxf', 'DXF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dessins', to='menuiserie.article')),
            ],
            options={
                'verbose_name': 'Dessin',
                'verbose_name_plural': 'Dessins',
                'db_table': 'menuiserie_dessins',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='menuiserie.projet'),
        ),
        migrations.AddField(
            model_name='article',
            name='tarif_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuiserie.tariffournisseur'),
        ),
    ]
