# Generated by Django 4.2.7 on 2025-11-07 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menuiserie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionMenuiserie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_option', models.CharField(choices=[('obligatoire', 'Obligatoire'), ('facultatif', 'Facultatif')], max_length=20)),
                ('type_article', models.CharField(choices=[('fenetre', 'Fenêtre'), ('porte', 'Porte'), ('baie', 'Baie vitrée'), ('autre', 'Autre'), ('tous', 'Tous')], default='tous', max_length=20)),
                ('ajout_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_prix_type', models.CharField(choices=[('fixe', 'Montant fixe'), ('pourcentage', 'Pourcentage'), ('aucun', 'Aucun')], default='aucun', max_length=20)),
                ('impact_prix_valeur', models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe en € ou pourcentage selon impact_prix_type', max_digits=10)),
                ('impact_dessin', models.JSONField(blank=True, default=dict, help_text="Paramètres pour modifier le dessin (ex: {ajout_element: 'ferrage', position: 'bas'})")),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option menuiserie',
                'verbose_name_plural': 'Options menuiserie',
                'db_table': 'menuiserie_options',
                'ordering': ['type_option', 'ordre_affichage', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='designation_base',
            field=models.CharField(blank=True, help_text='Désignation de base avant ajout des options', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='echelle_dessin',
            field=models.CharField(default='1:1', help_text='Échelle du dessin', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_base_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de base avant application des options', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='designation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='options_facultatives',
            field=models.JSONField(default=list, help_text='Liste des IDs des options facultatives sélectionnées'),
        ),
        migrations.AlterField(
            model_name='article',
            name='options_obligatoires',
            field=models.JSONField(default=list, help_text='Liste des IDs des options obligatoires sélectionnées'),
        ),
    ]
