# Generated by Django 4.2.7 on 2025-11-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerciale', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_visite', models.DateField()),
                ('type_visite', models.CharField(choices=[('prise_contact', 'Prise de contact'), ('devis', 'Devis'), ('suivi', 'Suivi'), ('relance', 'Relance')], max_length=20)),
                ('notes', models.TextField()),
                ('resultat', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='commerciale.client')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'db_table': 'crm_visites',
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('ca_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ca_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_devis', models.IntegerField(default=0)),
                ('nombre_factures', models.IntegerField(default=0)),
                ('famille_client', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_geographique', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='commerciale.client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'db_table': 'crm_statistiques',
            },
        ),
    ]
