# Generated by Django 4.2.7 on 2025-11-07 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visite',
            options={'ordering': ['-date_visite', '-created_at'], 'verbose_name': 'Visite', 'verbose_name_plural': 'Visites'},
        ),
        migrations.CreateModel(
            name='SuiviCA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('famille_article', models.CharField(max_length=100)),
                ('ca_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ca_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_devis', models.IntegerField(default=0)),
                ('nombre_factures', models.IntegerField(default=0)),
                ('nombre_clients', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suivi CA',
                'verbose_name_plural': 'Suivi CA',
                'db_table': 'crm_suivi_ca',
                'ordering': ['-periode_debut', '-periode_fin', 'famille_article'],
                'unique_together': {('periode_debut', 'periode_fin', 'famille_article')},
            },
        ),
    ]
