# Generated by Django 4.2.7 on 2025-11-07 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imprimante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom de l'imprimante", max_length=200)),
                ('type_imprimante', models.CharField(choices=[('locale', 'Locale'), ('reseau', 'Réseau')], default='locale', max_length=20)),
                ('nom_systeme', models.CharField(blank=True, help_text="Nom système de l'imprimante (ex: HP LaserJet Pro)", max_length=200, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'imprimante réseau", null=True)),
                ('port', models.IntegerField(default=9100, help_text="Port de l'imprimante réseau (par défaut: 9100 pour RAW, 515 pour LPR)")),
                ('protocole', models.CharField(choices=[('raw', 'RAW (Port 9100)'), ('lpr', 'LPR/LPD (Port 515)'), ('ipp', 'IPP (Port 631)'), ('http', 'HTTP')], default='raw', help_text="Protocole de communication avec l'imprimante réseau", max_length=20)),
                ('nom_reseau', models.CharField(blank=True, help_text="Nom réseau de l'imprimante (ex: \\\\SERVER\\PRINTER)", max_length=200, null=True)),
                ('format_papier', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('paysage', 'Paysage')], default='portrait', max_length=10)),
                ('actif', models.BooleanField(default=True, help_text='Imprimante active et disponible')),
                ('imprimante_par_defaut', models.BooleanField(default=False, help_text='Imprimante utilisée par défaut')),
                ('description', models.TextField(blank=True, help_text='Description ou notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imprimante',
                'verbose_name_plural': 'Imprimantes',
                'db_table': 'parametres_imprimantes',
                'ordering': ['nom'],
            },
        ),
    ]
