# Generated by Django 4.2.7 on 2025-11-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerciale', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type_vitrage', models.CharField(max_length=50)),
                ('epaisseur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficients', models.JSONField(default=dict)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration vitrage',
                'verbose_name_plural': 'Configurations vitrages',
                'db_table': 'vitrages_configurations',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_projet', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_vitrages', to='commerciale.chantier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_vitrages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet vitrage',
                'verbose_name_plural': 'Projets vitrages',
                'db_table': 'vitrages_projets',
            },
        ),
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epaisseur_vitrage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_vitrage', models.CharField(choices=[('monolithique', 'Monolithique'), ('feuilleté', 'Feuilleté'), ('isolation', 'Isolation'), ('autre', 'Autre')], max_length=20)),
                ('region_vent', models.CharField(max_length=50)),
                ('region_neige', models.CharField(max_length=50)),
                ('categorie_terrain', models.CharField(max_length=50)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('resultat_calcul', models.JSONField(default=dict)),
                ('norme_utilisee', models.CharField(default='NF DTU 39', max_length=50)),
                ('cahier_cstb', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs', to='vitrages.projet')),
            ],
            options={
                'verbose_name': 'Calcul vitrage',
                'verbose_name_plural': 'Calculs vitrages',
                'db_table': 'vitrages_calculs',
            },
        ),
    ]
