# Generated by Django 4.2.7 on 2025-11-07 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrages', '0001_initial'),
    ]

    operations = [
        # D'abord supprimer l'ancien modèle Calcul (et sa table)
        migrations.DeleteModel(
            name='Calcul',
        ),
        # Ensuite créer les nouveaux modèles
        migrations.CreateModel(
            name='RegionVentNeige',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_region', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('pression_vent_reference', models.DecimalField(decimal_places=2, max_digits=8)),
                ('charge_neige_reference', models.DecimalField(decimal_places=2, max_digits=8)),
                ('latitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Région vent/neige',
                'verbose_name_plural': 'Régions vent/neige',
                'db_table': 'vitrages_regions_vent_neige',
            },
        ),
        migrations.CreateModel(
            name='CategorieTerrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coefficient_exposition', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de terrain',
                'verbose_name_plural': 'Catégories de terrain',
                'db_table': 'vitrages_categories_terrain',
            },
        ),
        migrations.CreateModel(
            name='CalculVitrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_vitrage', models.CharField(choices=[('monolithique', 'Monolithique'), ('feuilleté', 'Feuilleté'), ('isolation', 'Isolation'), ('aquarium', 'Aquarium'), ('bassin', 'Bassin'), ('etagere', 'Étagère'), ('dalle_sol', 'Dalle de sol'), ('vea', 'VEA - Verre Extérieur Agrafé'), ('vec', 'VEC - Verre Extérieur Collé'), ('autre', 'Autre')], default='monolithique', max_length=50)),
                ('altitude', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pression_vent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('charge_neige', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('coefficient_securite', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('epaisseur_calculee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('epaisseur_recommandee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultat_calcul', models.JSONField(default=dict)),
                ('norme_utilisee', models.CharField(default='NF DTU 39 P4', max_length=100)),
                ('cahier_cstb', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('entete_personnalisee', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs', to='vitrages.projet')),
                ('region_vent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculs_vent', to='vitrages.regionventneige')),
                ('region_neige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculs_neige', to='vitrages.regionventneige')),
                ('categorie_terrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculs', to='vitrages.categorieterrain')),
            ],
            options={
                'verbose_name': 'Calcul vitrage',
                'verbose_name_plural': 'Calculs vitrages',
                'db_table': 'vitrages_calculs',
                'ordering': ['-created_at'],
            },
        ),
    ]
