# Generated by Django 4.2.7 on 2025-11-04 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pas de dépendance vers commerciale pour éviter la dépendance circulaire
        # Compte et Banque peuvent être créés indépendamment
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('numero_compte', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('bic', models.CharField(blank=True, max_length=11, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'db_table': 'comptabilite_banques',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_compte', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_compte', models.CharField(choices=[('classe1', 'Classe 1'), ('classe2', 'Classe 2'), ('classe3', 'Classe 3'), ('classe4', 'Classe 4'), ('classe5', 'Classe 5'), ('classe6', 'Classe 6'), ('classe7', 'Classe 7')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'db_table': 'comptabilite_comptes',
            },
        ),
        # Ecriture sera créé dans une migration séparée (0002) après commerciale.0002_initial
    ]
